# Generated by Django 4.2.7 on 2023-11-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelTesting', '0002_category_is_active_services_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='categories',
            field=models.ManyToManyField(related_name='Services', to='ModelTesting.category'),
        ),
    ]
