# Generated by Django 4.2.7 on 2023-11-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelTesting', '0007_alter_services_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='categories',
            field=models.ManyToManyField(related_name='services', to='ModelTesting.category'),
        ),
    ]
