# Generated by Django 4.2.7 on 2023-11-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelTesting', '0014_workflow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workflow',
        ),
    ]
