# Generated by Django 4.2.7 on 2023-11-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelTesting', '0011_pricing_services_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
