# Generated by Django 4.2.7 on 2023-11-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelTesting', '0012_pricing_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='form',
            field=models.ManyToManyField(related_name='services', to='ModelTesting.form'),
        ),
    ]
